### PR TITLE
Fixed test case

### PR DESCRIPTION
**Pull request by Frizz925**
Just realized the CI build has been failing for days now, just wanted to help a bit by fixing it.

### CODE REVIEW

**Comment by daurnimator** [comment]
Oops! Looks like I forgot to update the tests. Thanks for noticing!

Would you be able to change the tests to use the a destructuring assignment?

Also, please follow commit message convention of prefixing with the file(s) changed, and a short description of the change.

**Comment by Frizz925** [comment]
Is https://github.com/fengari-lua/fengari-interop/pull/28/commits/1219aec6767ae8d5490f62779c789900f2532e17 okay now? I tried following your src/jslib.js coding style.

**Comment by daurnimator** [comment]
It's a good start :)

I go one step further and localise all the functions used too.

Btw, could you edit your first commit's message?

**Comment by Frizz925** [comment]
Done :)

**Comment by daurnimator** [comment]
minor nit (I've done it before too!): you mispelled "destructured" in your commit message.

**Comment by daurnimator** [comment]
Thankyou for your contribution!

**Pull request merged**
