### PR TITLE
src/jslib.js: Add __pairs metamethod for JS objects

### PR DESCRIPTION
**Pull request by tysonclugg**

### CODE REVIEW

**Comment by daurnimator** [comment]
Thinking about this: as JS doesn't let us break it down into a plain 'next' operation: perhaps we should just have a new function `js.keys` which returns all the keys in a given object?
That object can then be iterated over as a normal lua object:

```lua
for _, k in ipairs(js.keys(myjsobject)) do
    print(k, myjsobject)
end
```

This lets us save `__pairs` for the JS `for...of` construction, which maps better to lua IMO (though it's new in ES6, so older JS apis haven't got support for it yet)

**Comment by daurnimator** [comment]
> a new function js.keys which returns all the keys in a given object?

This function would effectively be [`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys), (except that `Object.keys` doesn't iterate over prototype keys.... which is probably better). In which case I'm not sure it's worth even implementing? (as it provides nothing over just writing `js.global.Object:key(obj)`

**Comment by giann** [comment]
Do we close this ?

**Comment by daurnimator** [comment]
> Do we close this ?

I don't think so.

My current thinking is we create a well-known symbol for this.

**Pull request closed without merging**
