### PR TITLE
Call Function lazily to avoid triggering CSP

### LINKED ISSUE #64: Content-security-policy and use of Function
I'm adding fengari-web into an application that uses a Content-Security-Policy. The application has a simple policy of ```Content-Security-Policy: script-src 'self';```. However, because of this, the browser refuses to load fengari-web.js because of the use of ```Function``` to evaluate a string at this line:

https://github.com/fengari-lua/fengari-interop/blob/1626687fb15452cdd82ee522955dd1f144ea7a68/src/js.js#L701

The error is ```EvalError: call to Function() blocked by CSP```

I don't understand the Fangari code well enough to suggest a solution. Is there any way that the same could be achieved without evaluating code with the use of ```Function```?

As an experiment I tried replacing the above code with ```var make_arrow_function = function () {return ()=>void 0;}``` and everything ran as expected (although I realise this could lead to other problems as explained in the comments in the code).

Grateful for any assistance/comments. Many thanks.

### PR DESCRIPTION
**Pull request by daurnimator**
Closes #64

@abeverley

### CODE REVIEW

**Comment by abeverley** [comment]
I just wondered whether this will be merged soon or whether it is best for me to use directly from this branch? Many thanks.

**Comment by abeverley** [comment]
Sorry, @daurnimator would it also be possible to do a release to npm including this patch please? At the moment building fengari-web still pulls in the version without this fix. Thanks.

**Comment by daurnimator** [comment]
> Sorry, @daurnimator would it also be possible to do a release to npm including this patch please? At the moment building fengari-web still pulls in the version without this fix. Thanks.

Okay, lets give it a go. It's been a long time since a release! Lets see if I remember the process (also I suspect webpack will have broken in 10 novel ways)

**Comment by abeverley** [comment]
> Okay, lets give it a go. It's been a long time since a release!

Great, thanks! Grateful if you can let me know once it's done.

**Comment by abeverley** [comment]
Sorry, just wondered whether you can do the release if possible please...?

**Comment by daurnimator** [comment]
I did: https://github.com/fengari-lua/fengari-interop/releases/tag/v0.1.3

**Comment by abeverley** [comment]
Brilliant, thanks @daurnimator - just found, upgraded, built and all working nicely. Many thanks for your help.

**Pull request merged**
